---

devops_bucket: smartech-devops
deploy_bucket: smartech-deploy
devops_bucket_region: ap-south-1
deploy_bucket_region: ap-south-1

provision:
  git_url: 'https://corporate.netcore.co.in/gitbucket/git/Iac/smartech-infra-playbook.git'
  git_branch: onprem
  credentials_id: 92ad4c55-46ac-4def-988e-7b494c12f402
  jenkins_file: 
    default: 'jenkins/pipeline/provision.jenkinsfile'
    cloudfront: 'jenkins/pipeline/cloudfront_provision.jenkinsfile'
  region: [all, us, india]

build_deploy_config:
  jenkins_file: 'clouds/onprem/jenkins/seed-job/pipeline/app.jenkinsfile'
  merger_jenkins_file: 'clouds/onprem/jenkins/seed-job/pipeline/merger.jenkinsfile'
  git_url: 'https://corporate.netcore.co.in/gitbucket/git/Iac/smartech-svc.git'
  credentials_id: 92ad4c55-46ac-4def-988e-7b494c12f402
  git_branch: master
  tag_pattern: prod-cdp-
  vault_credential_id: ansible-cicd

  app_module:
    smartech-migration:
      git:
        server: https://gitlab.com/netcorecloud
        branch: master
        owner: cee
        repo_name: smartechMigration
        api: api/v3      
      credentials_id: git-cred of venkateshemandi
      lang_type: scripted
      app_type: core
      wrapper_dir: deployer
      sudoer_username: root
      connect_username: root
      host_credential_id: fa401864-ea5a-4fe3-bdb1-11b4086f28c7
      force_build: false
      notification:
        flock_url: https://api.flock.com/hooks/sendMessage/4ee04954-1230-4231-b677-39abcd0e233d
      build:
        dockerfile: 'deployer/docker/Dockerfile.build'
        artifact_dir: target
        build_dir: '.'
        build_args: '`eval "echo \--build-arg APP_COMMIT_ID=\\\$COMMIT_ID"`'
      unit_test:
        dockerfile: 'deployer/docker/Dockerfile.test'
        build_dir: '.'
        build_args: ' --no-cache '
      base_image:
        force_build: false
        dockerfile: 'deployer/docker/Dockerfile.baseImage'
        build_dir: '.'
        build_args: ''     

    storm-topologies:
      git:
        server: https://gitlab.com/netcorecloud
        branch: master
        owner: CDP
        repo_name: storm-topologies
        api: api/v3
      credentials_id: git-cred of venkateshemandi
      lang_type: compiled
      app_type: core
      wrapper_dir: deployer
      sudoer_username: root
      connect_username: root
      host_credential_id: fa401864-ea5a-4fe3-bdb1-11b4086f28c7
      force_build: false
      notification:
        flock_url: https://api.flock.com/hooks/sendMessage/4ee04954-1230-4231-b677-39abcd0e233d
      build:
        dockerfile: 'deployer/docker/Dockerfile.build'
        artifact_dir: target
        build_dir: '.'
        build_args: ''
      unit_test:
        dockerfile: 'deployer/docker/Dockerfile.test'
        build_dir: '.'
        build_args: ' --no-cache '
      base_image:
        force_build: false
        dockerfile: 'deployer/docker/Dockerfile.baseImage'
        build_dir: '.'
        build_args: ''    

    streamsets:
      git:
        server: https://gitlab.com/netcorecloud
        branch: master
        owner: CDP
        repo_name: streamsets
        api: api/v3
      credentials_id: git-cred of venkateshemandi
      lang_type: scripted
      app_type: core
      wrapper_dir: deployer
      sudoer_username: root
      connect_username: root
      host_credential_id: fa401864-ea5a-4fe3-bdb1-11b4086f28c7
      force_build: false
      notification:
        flock_url: https://api.flock.com/hooks/sendMessage/4ee04954-1230-4231-b677-39abcd0e233d
      unit_test:
        dockerfile: 'deployer/docker/Dockerfile.test'
        build_dir: '.'
        build_args: ' --no-cache '
      base_image:
        force_build: false
        dockerfile: 'deployer/docker/Dockerfile.baseImage'
        build_dir: '.'
        build_args: ''

    cdp-angular:
      git:
        server: https://gitlab.com/netcorecloud
        branch: master
        owner: CDP
        repo_name: cdp_angular
        api: api/v3      
      credentials_id: git-cred of venkateshemandi
      lang_type: compiled
      app_type: core
      wrapper_dir: deployer
      sudoer_username: root
      connect_username: root
      host_credential_id: fa401864-ea5a-4fe3-bdb1-11b4086f28c7
      force_build: false
      notification:
        flock_url: https://api.flock.com/hooks/sendMessage/4ee04954-1230-4231-b677-39abcd0e233d
      build:
        dockerfile: 'deployer/docker/Dockerfile.build'
        artifact_dir: target
        build_dir: '.'
        build_args: '`eval "echo \--build-arg CDN_URL=cdp-cdn.netcorecloud.com/abuild/ \--build-arg CONFIGURATION=production"`'
      unit_test:
        dockerfile: 'deployer/docker/Dockerfile.test'
        build_dir: '.'
        build_args: ' --no-cache '
      base_image:
        force_build: false
        dockerfile: 'deployer/docker/Dockerfile.baseImage'
        build_dir: '.'
        build_args: ''

    cdp-assets:
      git:
        server: https://gitlab.com/netcorecloud
        branch: master
        owner: CDP
        repo_name: cdp-assets
        api: api/v3      
      credentials_id: git-cred of venkateshemandi
      lang_type: scripted
      app_type: core
      wrapper_dir: deployer
      sudoer_username: root
      connect_username: root
      host_credential_id: fa401864-ea5a-4fe3-bdb1-11b4086f28c7
      force_build: false
      notification:
        flock_url: https://api.flock.com/hooks/sendMessage/4ee04954-1230-4231-b677-39abcd0e233d
      unit_test:
        dockerfile: 'deployer/docker/Dockerfile.test'
        build_dir: '.'
        build_args: ' --no-cache '
      base_image:
        force_build: false
        dockerfile: 'deployer/docker/Dockerfile.baseImage'
        build_dir: '.'
        build_args: ''

    storm-topologies-properties:
      git:
        server: https://gitlab.com/netcorecloud
        branch: master
        owner: CDP
        repo_name: storm-topologies
        api: api/v3
      credentials_id: git-cred of venkateshemandi
      lang_type: compiled
      app_type: core
      wrapper_dir: deployer
      sudoer_username: root
      connect_username: root
      host_credential_id: fa401864-ea5a-4fe3-bdb1-11b4086f28c7
      force_build: false
      notification:
        flock_url: https://api.flock.com/hooks/sendMessage/4ee04954-1230-4231-b677-39abcd0e233d
      build:
        dockerfile: 'deployer/docker/Dockerfile.build'
        artifact_dir: target
        build_dir: '.'
        build_args: ''
      unit_test:
        dockerfile: 'deployer/docker/Dockerfile.test'
        build_dir: '.'
        build_args: ' --no-cache '
      base_image:
        force_build: false
        dockerfile: 'deployer/docker/Dockerfile.baseImage'
        build_dir: '.'
        build_args: ''
